### ISSUE TITLE
Transfer to Firefox

### ISSUE THREAD

**Issue by Dustin-Jiang** [XFox111/TabsAsideExtension#28]
This extension is awesome and I wish it will be compatible with WebExtension APIs, which is used in Firefox, Safari and Opera's extension. 

WebExtension APIs is similar to Chrome Extension APIs, according to Mozilla Developer Network, and you can find documents at [MDN](https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions)

**Comment by XFox111** [comment]
Hi. Could you please test this version on Firefox? It seems to work fine on my machine but I just want to make sure

[TabsAside.zip](https://github.com/XFox111/ChromiumTabsAside/files/4953363/TabsAside.zip)

**Comment by Dustin-Jiang** [comment]
All right, I've installed it on my Firefox and almost everything works perfect, except the 'More...' button cannot work.

**Comment by XFox111** [comment]
> except the 'More...' button cannot work.

Hmm.. Seems fine to me. Can you please elaborate. It will be better if you also attach a video.

**Comment by Dustin-Jiang** [comment]
Sorry for forgetting replying this issue. 🙃 

![ScreenShot 2020-07-25 11 45 46](https://user-images.githubusercontent.com/56217843/88448420-8b7b6400-ce70-11ea-860e-ee83a855922d.png)
I'm sorry that I cannot upload a video to elaborate. When I click all the 'More...' buttons, which is marked in the image, there is no response and dropdown menus don't appear. I don't know if my explaination is clear enough and I hope you can find the problem. :)

**Comment by XFox111** [comment]
I don't know, seems to work for me. What's your browser version? Mine is 78.0.2 (the latest one)
![image](https://user-images.githubusercontent.com/28831743/88451032-4ea57200-ce5c-11ea-88e1-2be7b47ef58b.png)

**Comment by Dustin-Jiang** [comment]
That's strange. My Firefox version is also 78.0.2 (x86_64-apple-darwin on macOS 10.13, the latest version), and I'll try it later on Windows to see if it is caused by the differences between platforms.

**Comment by Dustin-Jiang** [comment]
All right, that's interesting because it can work properly on Windows (Firefox 78.0.2), and I don't know what's wrong on Mac. Maybe I'll reinstall Firefox on my Mac and try again.

**Comment by XFox111** [comment]
Do you have any other extensions on Mac which somehow alter web page content (e.g. Dark mode)?

I'll also check thin on Linux and post the results here

**Comment by Dustin-Jiang** [comment]
I installed Firefox Nightly (x86_64-apple-darwin, 81.0a1, 2020-07-28), which is brand new without any extensions, and tested the extension. Unfortunately, I found that the 'More' buttons still didn't work. I'll ask my friend who also has a Mac to test soon.

**Comment by XFox111** [comment]
> I'll also check thin on Linux and post the results here

On Linux it works as well on both Chromium and Firefox

**Comment by XFox111** [comment]
I've just done a new version and submitted it to [Chrome Webstore](https://chrome.google.com/webstore/detail/tabs-aside/mgmjbodjgijnebfgohlnjkegdpbdjgin), [Microsoft Edge Add-ons Webstore](https://microsoftedge.microsoft.com/addons/detail/kmnblllmalkiapkfknnlpobmjjdnlhnd) and [Mozilla Add-ons Webstore](https://addons.mozilla.org/en-US/firefox/addon/ms-edge-tabs-aside). It will take some time to pass the validation process. For now, you can download [latest version from GitHub Releases](https://github.com/xfox111/chromiumtabsaside/releases/latest) and test it.

Note that sideloaded extensions work as completely different ones so they don't interfere with officially installed extensions. It means that you don't have to remove the currently installed version

If context menus problem is still presented, I suggest you open a new issue, related to the specific problem. It seems that nobody else encounters it, so I see no reasons to postpone the extension's release on Firefox
