### ISSUE TITLE
Feature Request: Ability to rename Tab Groups

### ISSUE THREAD

**Issue by OttScott** [XFox111/TabsAsideExtension#33]
Feature Request to allow naming of Tab Groups set aside. This would allow me to know the purpose of the various tab groups I have archived weeks ago and recall their purpose. As it is currently implemented, I have to read the site names of the preview listing and try to remember _why_ I was looking at them or set them aside. With a rename feature, I could easily track the purpose of the groupings to know which I wanted to reopen at the time.

Excellent addon.

**Comment by XFox111** [comment]
Thanks for using my extension. I appreciate it) 

I've just completed the PR and submitted the new version to [Chrome Webstore](https://chrome.google.com/webstore/detail/tabs-aside/mgmjbodjgijnebfgohlnjkegdpbdjgin), [Microsoft Edge Add-ons Webstore](https://microsoftedge.microsoft.com/addons/detail/kmnblllmalkiapkfknnlpobmjjdnlhnd) and [Firefox Add-ons Webstore](https://addons.mozilla.org/firefox/addon/ms-edge-tabs-aside/). It has already been approved in both Chrome and FIrefox stores and will be available soon on Microsoft Edge. You can also download [latest version from GitHub Releases](https://github.com/xfox111/chromiumtabsaside/releases/latest) and test it.

Note that sideloaded extensions work as completely different ones so they don't interfere with officially installed extensions. It means that you don't have to remove the currently installed version
