### ISSUE TITLE
List view

### ISSUE THREAD

**Issue by macgyverkam** [XFox111/TabsAsideExtension#35]
Ability to switch between thumbnails view and list (something like onetab has: [https://www.one-tab.com/web/images/home/before-after2019.jpg](url) )

**Comment by XFox111** [comment]
Thanks for using my extension. I appreciate it) 

I've just completed new version and submitted to [Chrome Webstore](https://chrome.google.com/webstore/detail/tabs-aside/mgmjbodjgijnebfgohlnjkegdpbdjgin), [Microsoft Edge Add-ons Webstore](https://microsoftedge.microsoft.com/addons/detail/kmnblllmalkiapkfknnlpobmjjdnlhnd) and [Firefox Add-ons Webstore](https://addons.mozilla.org/firefox/addon/ms-edge-tabs-aside/). It has already been approved in both Chrome and FIrefox stores and will be available soon on Microsoft Edge. You can also download [latest version from GitHub Releases](https://github.com/xfox111/chromiumtabsaside/releases/latest) and test it.

Note that sideloaded extensions work as completely different ones so they don't interfere with officially installed extensions. It means that you don't have to remove the currently installed version

**Comment by macgyverkam** [comment]
Wooohooooo! XFox111 big thx!
