### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by Wafflects** [XFox111/TabsAsideExtension#37]
I took my time to translate the extension to Spanish

[es.zip](https://github.com/XFox111/TabsAsideExtension/files/5146107/es.zip)

**Comment by XFox111** [comment]
Hi. Thanks for your contribution to the project!
Unfortunately, I don't know Spanish, so I only can rely on Google Translator. I've added some comments in the PR in places I consider questionable. Could you please check them and explain to me why they are correct (or update them if they are not)?
