### ISSUE TITLE
Sync feature?

### ISSUE THREAD

**Issue by lokize** [XFox111/TabsAsideExtension#39]
Nice extension for chromium, its possible to sync in future?

**Comment by XFox111** [comment]
Hi, thanks for your suggestion!
This feature was planned a long time ago and it's definitely a useful one. But it also requires some computing and storage resources as well as complex and secured architecture to keep your personal data from anyone else. The first two things I'm probably able to obtain but the last one requires some time and research. I'll continue the work but keep in mind that it can take a bit more time than we'd like to

**Comment by AmineI** [comment]
Couldn't we just store the data in chrome [storage.sync](https://developer.chrome.com/extensions/storage#property-sync) ? I know it has quite a few limitations however, so it may be fairly limited. Screenshots, for example, would easily kill the quota, but I think the basic collections may work.

**Comment by XFox111** [comment]
@AmineI good point. I just didn't know that `storage.sync` do work across devices. Then it should be quite easy

**Comment by AmineI** [comment]
Yep, here's the relevant paragraph from the docs link above : 

> When using storage.sync, the stored data will automatically be synced to any Chrome browser that the user is logged into, provided the user has sync enabled.
> 
> When Chrome is offline, Chrome stores the data locally. The next time the browser is online, Chrome syncs the data. Even if a user disables syncing, storage.sync will still work. In this case, it will behave identically to storage.local.
> Confidential user information should not be stored! The storage area isn't encrypted.

It also syncs for other chromium browsers, such as the Chromium Edge, provided they have a backend set up for that.

I hope it won't easily have conflicts between machines and lose data, though, we'll have to test a few scenarios to make sure of that.

**Comment by AmineI** [comment]
This [stackoverflow answer](https://stackoverflow.com/a/23249383) by the API author is quite informative about their merge mechanisms, and may prove useful later. 

Basically, if a collection is guaranteed to have a unique key (that would include the datetime for example) in the storage area, and considering we can't add a tab to an existing collection, then data loss should never happen in our case.

**Comment by AmineI** [comment]
Some people found a lot of interesting things about the sync storage, and some contradict the info from the link above. Here are their findings :
 https://github.com/mozilla/application-services/issues/2900

**Comment by XFox111** [comment]
@AmineI I've created new branch for the feature and moved changes there. See PR #47

**Comment by Dustin-Jiang** [comment]
I found docs in MDN and it said that `storage.sync` is supported by Firefox as well since Firefox 53, and you can find more information [here](https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync).

**Comment by XFox111** [comment]
Hey @lokize, thanks for using my extension! I appreciate it) 

I've just submitted a new version to [Chrome Webstore](https://chrome.google.com/webstore/detail/tabs-aside/mgmjbodjgijnebfgohlnjkegdpbdjgin), [Microsoft Edge Add-ons Webstore](https://microsoftedge.microsoft.com/addons/detail/kmnblllmalkiapkfknnlpobmjjdnlhnd) and [Firefox Add-ons Webstore](https://addons.mozilla.org/firefox/addon/ms-edge-tabs-aside/). It has already been approved in Firefox store and still awaits validation for the other ones
