### ISSUE TITLE
Ability to disable the context menu entry

### ISSUE THREAD

**Issue by AmineI** [XFox111/TabsAsideExtension#41]
Users with many extensions tend to have a bloated context menus due to each extensions entries. 

To help with that, many extensions allow to disable the context menu entries. 

I think it'd be welcome to have to ability to disable or enable the context menu entries for this extension

**Comment by XFox111** [comment]
I'm not sure if this is possible since context menu entries are declared in the manifest

**Comment by AmineI** [comment]
Ah ? I should have clarified but I'm thinking about the context menu when you right click on a *webpage*. Maybe there is a programmatic way to declare them, since i have quite a few extensions that offer this, such as https://github.com/greatsuspender/thegreatsuspender . I'll look around to see if it could be done here.

**Comment by AmineI** [comment]
Yes, it's using the chrome.contextMenus api, we may not be talking about the same context menu.

For this context menu we'd just have to put these lines in a condition block.
https://github.com/XFox111/TabsAsideExtension/blob/3e605834279db7bca0846da1b8822452bc76a588/js/background.js#L74-L88 

But that's if you think this addition is relevant, of course - if you don't want another setting in your extension it's understandable as well !

**Comment by XFox111** [comment]
Yeah, I think you're right. But instead of making an option to disable the menu I think it would be better to just cut it off from page - another almost-useless-option to the settings menu won't be a great idea

**Comment by AmineI** [comment]
Yeah removing it completely from page would be fine, I don't think it's used that much since we have the action button + shortcuts, but you added that feature this summer so I assumed some people needed it. Your choice :) !
