### ISSUE TITLE
Add Brazilian Portuguese on this extension

### ISSUE THREAD

**Issue by amandafilizola** [XFox111/TabsAsideExtension#53]
**Is your feature request related to a problem? Please describe.**
No, only adding new internationalization.

**Describe the solution you'd like**
One pt_BR folder on _locales. So it automatically opens up on browsers with pt_BR default.

**Describe alternatives you've considered**
One pt_BR folder on _locales.

Already tested the changes locally Chrome browser. Please assign it to me when accepted.

**Comment by XFox111** [comment]
All, clear. As soon as you make sure all things work correctly, please create a PR into `major-2.0` branch instead of `master`

**Comment by amandafilizola** [comment]
#54 is open to major-2.0

**Comment by XFox111** [comment]
Thanks for your contribution to the project!

I've just completed new version and submitted to [Chrome Webstore](https://chrome.google.com/webstore/detail/tabs-aside/mgmjbodjgijnebfgohlnjkegdpbdjgin), [Microsoft Edge Add-ons Webstore](https://microsoftedge.microsoft.com/addons/detail/kmnblllmalkiapkfknnlpobmjjdnlhnd) and [Firefox Add-ons Webstore](https://addons.mozilla.org/firefox/addon/ms-edge-tabs-aside/). It has already been approved in both Chrome and FIrefox stores and will be available soon on Microsoft Edge. You can also download [latest version from GitHub Releases](https://github.com/xfox111/chromiumtabsaside/releases/latest) and test it.

Note that sideloaded extensions work as completely different ones so they don't interfere with officially installed extensions. It means that you don't have to remove the currently installed version
