### ISSUE TITLE
Cross-Theme icon

### ISSUE THREAD

**Issue by akhilesh-balaji** [XFox111/TabsAsideExtension#55]
**Is your feature request related to a problem? Please describe.**
I don't have the dark mode turned on in MS Edge. I do, however, have a dark "theme" for microsoft edge, so that only my tabs, omnibox, and download bar have a dark theme, as seen here:
![image](https://user-images.githubusercontent.com/69246693/98527732-64bb2f00-22a1-11eb-9cdb-c13ec39f8918.png)

However, the extension doesn't seem to realize that I have a dark "theme", and continues using the light theme icon, which is not clearly visible, as seen in the screenshot.

**Describe the solution you'd like**
My suggestion is to have a cross-theme compatible icon that can be turned on by the user if they feel that the icon is not visible. I have prepared one such icon which follows a neutral theme:
![newicon](https://user-images.githubusercontent.com/69246693/98528101-dabf9600-22a1-11eb-8775-97bd7792b11b.png)

**Comment by XFox111** [comment]
Wow. Looks amazing. I think it will be a fantastic addition to the project! I'll be glad to add this to the next version

So, to do this we need a few steps to make
- If you want to make a PR yourself, I can assign you to the issue (keep in mind that since there's an upcoming version already, you need to make a PR into a `major-2.0` branch)
- And if you want, you can leave it to me, but I need you to provide a source of the icon then

**Comment by akhilesh-balaji** [comment]
I don't have much experience with PRs, so I would prefer that you did it. [Here's](https://we.tl/t-oVk7ORAkzo) a link to the SVG file (GitHub doesn't support attaching them).

**Comment by XFox111** [comment]
Thank you for being interested in my project! It's really important to me.
Your changes have been merged into 2.0 version branch and will be published as soon as the version will be ready to deliver

**Comment by XFox111** [comment]
Thanks for your contribution to the project

I've just completed new version and submitted to [Chrome Webstore](https://chrome.google.com/webstore/detail/tabs-aside/mgmjbodjgijnebfgohlnjkegdpbdjgin), [Microsoft Edge Add-ons Webstore](https://microsoftedge.microsoft.com/addons/detail/kmnblllmalkiapkfknnlpobmjjdnlhnd) and [Firefox Add-ons Webstore](https://addons.mozilla.org/firefox/addon/ms-edge-tabs-aside/). It has already been approved in both Chrome and FIrefox stores and will be available soon on Microsoft Edge. You can also download [latest version from GitHub Releases](https://github.com/xfox111/chromiumtabsaside/releases/latest) and test it.

Note that sideloaded extensions work as completely different ones so they don't interfere with officially installed extensions. It means that you don't have to remove the currently installed version

**Comment by dberezansky** [comment]
Is there any chance that there will be a choice added in the settings for the original icon vs the cross-theme compatible icon? 
![image](https://user-images.githubusercontent.com/23129330/109863753-dfc0a080-7c16-11eb-8d9b-aad3b506048b.png) vs ![image](https://user-images.githubusercontent.com/23129330/109863689-ccadd080-7c16-11eb-814b-31c60d40b877.png) I do not have a theme in place on my browser and I beleive that the original icon actually looked a bit sharper when there is no theme in place. Thank you for your work on this project!

**Comment by XFox111** [comment]
@dberezansky Hi, thanks for your feedback! Personally, I like these simple icons as well since this is more consistent and meets Windows design system. But these icons are much harder to maintain - more complex code and less reliable product. So I don't think it is good idea to go back to the old style

**Comment by dberezansky** [comment]
@XFox111 That sounds very reasonable! I like these icons for pretty much the same reasons. Thank you for the consideration and I really appreciate the work you did for this extension!
