### ISSUE TITLE
Option to set aside tabs without closing them

### ISSUE THREAD

**Issue by gitdine** [XFox111/TabsAsideExtension#65]
There are times when I want to set aside my current session without closing the tabs, this would be good to have as an option.

**Comment by XFox111** [comment]
Hi, thanks for your suggestion
It could be a useful feature if this extension hadn't been designed to be a temporary storage for tabs. The point of the extension is to be able to take a break from your current tasks, close opened tabs, restore them as soon as you will be ready to continue and then close them completely after fining the tasks

If you think you still need this feature, you should consider using browser bookmarks or you can try out new Microsoft Edge's Collections which have the exact same feature you need

**Comment by XFox111** [comment]
Hi, thanks for your suggestion
It could be a useful feature if this extension hadn't been designed to be a temporary storage for tabs. The point of the extension is to be able to take a break from your current tasks, close opened tabs, restore them as soon as you will be ready to continue and then close them completely after fining the tasks. If you think you still need these features you should consider using browser bookmarks or you can try out new Microsoft Edge with "Collections" feature which works exactly as you've described
