### ISSUE TITLE
translation -> Polish

### ISSUE THREAD

**Issue by p0k33m0n** [XFox111/TabsAsideExtension#80]
Hi,

Great extension. Possible to translate to Polish?

Greetings.

**Comment by XFox111** [comment]
Hi, thank you for your suggestion!

Adding new languages is always important task. However, I don't think that putting it into google translator will be a good idea. So, all existing translations are manually made by contributors

Unfortunately, I don't know Polish, so if you want to work on the translation you can ask to be assigned on the issue or you can wait someone to do it

**Comment by p0k33m0n** [comment]
But I know Polish. :)

**Comment by XFox111** [comment]
So, you want to take this task?

**Comment by p0k33m0n** [comment]
Exactly. This is easy task. I translated eg. Boot-US boot interface or some (smaller) extensions for FF.

**Comment by XFox111** [comment]
Cool! That would be great!
