### ISSUE TITLE
"Restore without removing" button at incorrect position

### ISSUE THREAD

**Issue by XonFire** [XFox111/TabsAsideExtension#87]
Version:
Microsoft Edge Version 93.0.961.52 (Official build) (64-bit)
Restore without removing button is at the wrong position from the third entry (from the top) onwards. This distance seems to be increasing the further down the position of the group (by the forth/fifth entry the restore without removing button is out of screen)
![image](https://user-images.githubusercontent.com/60282894/133726823-6f05db09-c927-4a72-9dec-9afdaabca946.png)
![image](https://user-images.githubusercontent.com/60282894/133726895-54f6318a-10af-45dc-a30f-50fde016d790.png)

**Comment by XonFire** [comment]
And thanks for making this extension btw! I love it thoroughly! :)

**Comment by XFox111** [comment]
Hi. I'm glad that you liked it :)
I've managed to reproduce the bug. Will roll out fix as soon as possible 🚀

**Comment by XFox111** [comment]
Seems to be fixed. I've pushed new version to master. Should take some time to get delivered to webstores. In a meantime you can try out [latest release here](https://github.com/XFox111/TabsAsideExtension/releases/latest) and make sure it's fixed for you

**Comment by XonFire** [comment]
Okay thank you very much!
