### ISSUE TITLE
Tab collection renaming - Automatically lose focus on enter

### ISSUE THREAD

**Issue by jorgengaldal** [XFox111/TabsAsideExtension#93]
When renaming tab collections, I always find myself hitting enter, but nothing happens.

It would be nice if the name field lost focus on enter.

**Comment by XFox111** [comment]
Hi, thanks for your feedback. At the moment I'm actively working on a new major update for the extension which will bring completely new UI/UX. So, I'll keep that in mind, though your issue may become irrelevant when the update comes out
